name: Java CI with Gradle and Docker Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR File with Gradle
        run: ./gradlew clean build

      - name: Verify JAR File
        run: ls -l build/libs/

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/web-library:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/web-library:latest ${{ secrets.DOCKER_USERNAME }}/web-library:$(date +%Y%m%d%H%M)

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/web-library:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/web-library:$(date +%Y%m%d%H%M)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/web-library:latest
            docker-compose down || true  # 기존 컨테이너 중지 (없어도 계속 진행)
            docker-compose up -d --remove-orphans