# 워크플로우 이름을 정의합니다.
name: Java CI with Gradle

# 이 워크플로우가 실행될 조건(이벤트)을 설정합니다.
on:
  # main 브랜치에 코드가 푸시(push)될 때 실행됩니다.
  push:
    branches: [ main ]
  # main 브랜치를 대상으로 하는 pull request가 생성되거나 업데이트될 때 실행됩니다.
  pull_request:
    branches: [ main ]

# 실행할 작업(jobs)을 정의합니다.
jobs:
  # 'build'라는 이름의 작업(job)을 정의합니다.
  build:
    # 이 작업은 최신 Ubuntu 환경에서 실행됩니다.
    runs-on: ubuntu-latest

    # 작업 내에서 순차적으로 실행될 단계(steps)를 나열합니다.
    steps:
      # 리포지토리를 체크아웃(다운로드)하는 단계입니다.
      - name: Checkout repository
        uses: actions/checkout@v3  # GitHub에서 제공하는 checkout 액션을 사용해 소스 코드를 가져옵니다.

      # JDK 17을 설치하고 설정하는 단계입니다.
      - name: Set up JDK 17
        uses: actions/setup-java@v3  # GitHub의 setup-java 액션을 사용해 JDK를 설치합니다.
        with:
          java-version: '17'       # 설치할 자바 버전을 17로 지정합니다.
          distribution: 'temurin'  # Temurin 배포판을 사용하여 JDK를 설치합니다.

      # gradlew 스크립트에 실행 권한을 부여하는 단계입니다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew   # gradlew 파일에 실행 권한을 추가합니다.

      # Gradle 명령어를 실행하여 프로젝트를 빌드하고 테스트를 수행하는 단계입니다.
      - name: Build and run tests
        run: ./gradlew clean test  # gradlew를 통해 클린 빌드 후, 테스트를 실행합니다.